# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mkt-data.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'mkt-data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emkt-data.proto\"k\n\x06Ticker\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06sector\x18\x03 \x01(\t\x12\x1d\n\x04type\x18\x04 \x01(\x0e\x32\x0f.InstrumentType\x12\x14\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\x06.Value\"$\n\x05Value\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\"Y\n\nInvestment\x12\x17\n\x06ticker\x18\x01 \x01(\x0b\x32\x07.Ticker\x12\x0b\n\x03qty\x18\x02 \x01(\x01\x12!\n\x0b\x61\x63\x63ountType\x18\x03 \x01(\x0e\x32\x0c.AccountType:\x02\x18\x01\"U\n\nInstrument\x12\x17\n\x06ticker\x18\x01 \x01(\x0b\x32\x07.Ticker\x12\x0b\n\x03qty\x18\x02 \x01(\x01\x12!\n\x0b\x61\x63\x63ountType\x18\x03 \x01(\x0e\x32\x0c.AccountType\"S\n\tPortfolio\x12$\n\x0binvestments\x18\x01 \x03(\x0b\x32\x0b.InvestmentB\x02\x18\x01\x12 \n\x0binstruments\x18\x02 \x03(\x0b\x32\x0b.Instrument*(\n\x0b\x41\x63\x63ountType\x12\x08\n\x04TFSA\x10\x00\x12\x06\n\x02NR\x10\x01\x12\x07\n\x03IND\x10\x03*z\n\x0eInstrumentType\x12\n\n\x06\x45QUITY\x10\x00\x12\t\n\x05INDEX\x10\x01\x12\x07\n\x03\x45TF\x10\x02\x12\x0e\n\nMUTUALFUND\x10\x03\x12\n\n\x06\x46UTURE\x10\x04\x12\x0c\n\x08\x43URRENCY\x10\x05\x12\x12\n\x0e\x43RYPTOCURRENCY\x10\x06\x12\n\n\x06OPTION\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mkt_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVESTMENT']._loaded_options = None
  _globals['_INVESTMENT']._serialized_options = b'\030\001'
  _globals['_PORTFOLIO'].fields_by_name['investments']._loaded_options = None
  _globals['_PORTFOLIO'].fields_by_name['investments']._serialized_options = b'\030\001'
  _globals['_ACCOUNTTYPE']._serialized_start=428
  _globals['_ACCOUNTTYPE']._serialized_end=468
  _globals['_INSTRUMENTTYPE']._serialized_start=470
  _globals['_INSTRUMENTTYPE']._serialized_end=592
  _globals['_TICKER']._serialized_start=18
  _globals['_TICKER']._serialized_end=125
  _globals['_VALUE']._serialized_start=127
  _globals['_VALUE']._serialized_end=163
  _globals['_INVESTMENT']._serialized_start=165
  _globals['_INVESTMENT']._serialized_end=254
  _globals['_INSTRUMENT']._serialized_start=256
  _globals['_INSTRUMENT']._serialized_end=341
  _globals['_PORTFOLIO']._serialized_start=343
  _globals['_PORTFOLIO']._serialized_end=426
# @@protoc_insertion_point(module_scope)
