# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mkt-data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emkt-data.proto\"L\n\x06Ticker\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06sector\x18\x03 \x01(\t\x12\x14\n\x04\x64\x61ta\x18\x04 \x03(\x0b\x32\x06.Value\"$\n\x05Value\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mkt_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TICKER']._serialized_start=18
  _globals['_TICKER']._serialized_end=94
  _globals['_VALUE']._serialized_start=96
  _globals['_VALUE']._serialized_end=132
# @@protoc_insertion_point(module_scope)
